### ISSUE TITLE
Set default for strict to false

### ISSUE THREAD

**Issue by MasterOdin** [sqlectron/sql-query-identifier#38]
In both sqlectron and beekeeper-studio, it looks like we pretty universally use sql-query-identifier with `strict: false`. I propose just making that the default as it's probably the better behavior than throwing an exception in the context of analyzing it before running it, especially given that this library does not implement a true AST for the supported dialects. Can put this in v3 which would contain the breaking change discussed in https://github.com/sqlectron/sql-query-identifier/pull/33#discussion_r671733617.

Thoughts @rathboma?

**Comment by rathboma** [comment]
Yes! Agreed.
